### ISSUE TITLE
Curl problem

### ISSUE THREAD

**Issue by Silenoz93** [walcony/letsencrypt-DuckDNS-hook#1]
Hello,
I tried your "hook" and had some problems.
First problem was that the command "curl -X PUT" didn't work for me, so I did use just curl with the path in apostrophs, which did work for me.
e.g.:
`curl "https://www.duckdns.org/updateomains=${DOMAIN}&token=${DUCKDNS_TOKEN}&txt=removed&clear=true"`

My second problem is that after certificate creation, i still get the error _KEYFILE: unbound variable_
such as below...
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
/etc/dehydrated/hooks/duckdns/hook.sh: line 32: KEYFILE: unbound variable

maybe you can help me?
BTW. I'm using a raspberrypi 2 with raspbian buster
Best regards and thank you!

**Comment by YasharF** [comment]
Looking at https://github.com/SeattleDevs/letsencrypt-DuckDNS-hook/blob/master/hook.sh#L32 it looks like the current script is trying to deploy to nginx which you may not have.  I would be happy to either accept documentation or code PR if you would like to create one.

Regarding the curl issue, can you provide the version of your curl?  `curl -V`
Can you also check to see if -X is a defined command for your version of curl?  `curl -h`

**Comment by Silenoz93** [comment]
Thanks for looking into my issue!

I found the problem causing the unbound variable error! 
I had to add following line to the deploy_cert class...
`local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" FULLCHAINFILE="${4}" CHAINFILE="${5}"`

Curl Version is 7.64.0 (arm-unknown-linux-gnueabihf)

Curl -X is defined as:
 -X, --request <command> Specify request command to use
     --request-target Specify the target for this request
     --resolve <host:port:address[,address]...> Resolve the host+port to this address
     --retry <num>   Retry request if transient problems occur
     --retry-connrefused Retry on connection refused (use with --retry)
     --retry-delay <seconds> Wait time between retries
     --retry-max-time <seconds> Retry only within this period
     --sasl-ir       Enable initial response in SASL authentication
     --service-name <name> SPNEGO service name

I will add a Code PR without curl-X and the fix for the unboud variable...
